import mongoose from "mongoose";

/*
 * Mongoose model for storing short links.  Each document stores a unique slug
 * (generated by nanoid), the original target URL and the number of clicks.
 */

const LinkSchema = new mongoose.Schema(
  {
    slug: {
      type: String,
      unique: true,
      index: true
    },
    target: {
      type: String,
      required: true
    },
    clicks: {
      type: Number,
      default: 0
    }
  },
  { timestamps: true }
);

export default mongoose.model("Link", LinkSchema);